version: '3.4'

networks:
  filmker:
    external: false

services:
  db:
    image: postgres:latest
    ports:
      - 5445:5432
    
    restart: always
    volumes:
      - ./db:/var/lib/postresql/data
    command:
      ["postgres", "-c", "log_statement=none", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: "FilMaker"
      POSTGRES_PASSWORD: "TesTIngPAssWordDevOnly"
      POSTGRES_DB: "FilMaker"
    networks:
      - filmker